from collections.abc import Generator

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_ollama import ChatOllama

from src.config import (
    DEFAULT_MAX_TOKENS,
    DEFAULT_REPEAT_PENALTY,
    DEFAULT_TEMPERATURE,
    DEFAULT_TOP_P,
    OLLAMA_BASE_URL,
)


class ChatEngine:
    """Handles LLM chat interactions via LangChain and Ollama."""

    def __init__(
        self,
        model_name: str,
        system_prompt: str = "",
        temperature: float = DEFAULT_TEMPERATURE,
        max_tokens: int = DEFAULT_MAX_TOKENS,
        top_p: float = DEFAULT_TOP_P,
        repeat_penalty: float = DEFAULT_REPEAT_PENALTY,
        base_url: str = OLLAMA_BASE_URL,
    ):
        self.model_name = model_name
        self.system_prompt = system_prompt
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.top_p = top_p
        self.repeat_penalty = repeat_penalty
        self.base_url = base_url
        self._llm = self._create_llm()

    def _create_llm(self) -> ChatOllama:
        """Create a ChatOllama instance with current settings."""
        return ChatOllama(
            model=self.model_name,
            base_url=self.base_url,
            temperature=self.temperature,
            num_predict=self.max_tokens,
            top_p=self.top_p,
            repeat_penalty=self.repeat_penalty,
        )

    @staticmethod
    def _convert_messages(messages: list[dict]) -> list:
        """Convert simple message dicts to LangChain message objects."""
        lc_messages = []
        for msg in messages:
            role = msg["role"]
            content = msg["content"]
            if role == "system":
                lc_messages.append(SystemMessage(content=content))
            elif role == "user":
                lc_messages.append(HumanMessage(content=content))
            elif role == "assistant":
                lc_messages.append(AIMessage(content=content))
        return lc_messages

    def _build_messages(self, messages: list[dict]) -> list:
        """Build the full message list including the system prompt."""
        full_messages = []
        if self.system_prompt:
            full_messages.append({"role": "system", "content": self.system_prompt})
        full_messages.extend(messages)
        return self._convert_messages(full_messages)

    def stream_response(self, messages: list[dict]) -> Generator[str, None, None]:
        """Stream a response token-by-token.

        Yields string chunks as they are generated by the model.
        """
        lc_messages = self._build_messages(messages)
        for chunk in self._llm.stream(lc_messages):
            if chunk.content:
                yield chunk.content

    def get_response(self, messages: list[dict]) -> str:
        """Get a complete (non-streaming) response."""
        lc_messages = self._build_messages(messages)
        response = self._llm.invoke(lc_messages)
        return response.content

    def update_model(self, model_name: str) -> None:
        """Switch to a different model."""
        self.model_name = model_name
        self._llm = self._create_llm()

    def update_parameters(
        self,
        temperature: float | None = None,
        max_tokens: int | None = None,
        top_p: float | None = None,
        repeat_penalty: float | None = None,
    ) -> None:
        """Update model generation parameters."""
        if temperature is not None:
            self.temperature = temperature
        if max_tokens is not None:
            self.max_tokens = max_tokens
        if top_p is not None:
            self.top_p = top_p
        if repeat_penalty is not None:
            self.repeat_penalty = repeat_penalty
        self._llm = self._create_llm()
